spring.application.name=consuming-rest
server.port=8081
superhero.api.base-url=http://localhost:8080
spring.cloud.openfeign.okhttp.enabled=true

resilience4j.circuitbreaker.instances.HeroServiceClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.HeroServiceClient.slow-call-rate-threshold=80
resilience4j.circuitbreaker.instances.HeroServiceClient.slow-call-duration-threshold=2s
resilience4j.circuitbreaker.instances.HeroServiceClient.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.HeroServiceClient.sliding-window-size=5
resilience4j.circuitbreaker.instances.HeroServiceClient.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.HeroServiceClient.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.HeroServiceClient.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.HeroServiceClient.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.HeroServiceClient.register-health-indicator=true

resilience4j.retry.instances.HeroServiceClient.max-attempsts=3
resilience4j.retry.instances.HeroServiceClient.wait-duration=10000ms

#multiply time by 2
resilience4j.retry.instances.HeroServiceClient.exponentialBackoffMultiplier=2.0
resilience4j.retry.instances.HeroServiceClient.enable-exponential-backoff=true

#ignore bad requests
resilience4j.retry.instances.HeroServiceClient.retryExceptions = org.springframework.web.client.HttpServerErrorException.ServiceUnavailable


#Rate limiter
resilience4j.retry.instances.HeroServiceClient.limitForPeriod= 3
resilience4j.retry.instances.HeroServiceClient.limitRefreshPeriod= 1000ms
resilience4j.retry.instances.HeroServiceClient.timeoutDuration= 500ms


superhero.auth-url=http://localhost:8080/auth/login
superhero.username=consuming-rest-client
superhero.password=12345



resilience4j.circuitbreaker.configs.default.sliding-window-size=5
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=5
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.configs.default.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.HeroServiceClient.base-config=default


management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents
management.health.circuitbreakers.enabled=true
resilience4j.circuitbreaker.configs.default.register-health-indicator=true
